version: "3"
services:
  client:
    build: ./client
    volumes:
      - ./client:/home/node/client
      - /home/node/client/node_modules
    depends_on:
      - api
  api:
    build: ./server
    env_file:
      - .env
    volumes:
      - ./server:/home/node/server
      - /home/node/server/node_modules
    depends_on:
      - postgres
      - gojudge
  postgres:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - /var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_DB_DRIVER=pgsql
    depends_on:
      - postgres
  nginx:
    image: nginx:1.21.4
    ports:
      - 80:80
    depends_on:
      - api
      - client
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass IMTIAZCHO
    volumes: 
      - cache:/data

  gojudge:
    build: 
      context: ./server
      dockerfile: Dockerfile.exec
    privileged: true
    ports: 
      - 5050:5050

volumes:
  cache:
    driver: local

