version: "3.7"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=proghours
      - TZ=Asia/Dhaka
      - PGTZ=Asia/Dhaka
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
    networks:
      - proghours

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - proghours

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - /var/lib/redis/data
    networks:
      - proghours

networks:
  proghours:
    driver: bridge
