version: "3.7"
services:
  postgres:
    image: postgres:15.6-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=proghours
      - TZ=Asia/Dhaka
      - PGTZ=Asia/Dhaka
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
    networks:
      - proghours

  pgadmin:
    image: dpage/pgadmin4:8.3
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: naimulcsx@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    ports:
      - "8800:80"
    volumes:
      - /var/lib/pgadmin

  adminer:
    image: adminer:4.8.1
    restart: unless-stopped
    ports:
      - 8888:8080
    networks:
      - proghours

  redis:
    image: redis:7.2.4-alpine
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - /var/lib/redis/data

networks:
  proghours:
    driver: bridge
