-- AlterTable
ALTER TABLE "problems" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMP(0),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "pull_histories" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMP(0),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "pull_history_items" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMP(0),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "submissions" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMP(0),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "users" ALTER COLUMN "last_seen" SET DATA TYPE TIMESTAMP(0),
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMP(0),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMP(0);
