POST http://localhost/nest-api/submissions
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJDMTgxMDY1IiwibmFtZSI6Ik5haW11bCBIYXF1ZSIsImlhdCI6MTY0NTc1NzU4OH0.7y0EqRdar4GSVLYssrfbphOKvuEQly-P0cdRZVK41is;
Content-Type: application/json

{
  "link": "https://codeforces.com/contest/1617/problem/A",
  "solve_time": 65,
  "verdict": "AC",
  "solved_at": "2022-02-25T02:57:28.354Z"
}