POST http://localhost/nest-api/auth/register
Content-Type: application/json

{
  "name": "Fahim Shahrier",
  "email": "fahim@gmail.com",
  "password": "test1234",
  "username": "C181059"
}

###
POST http://localhost/nest-api/auth/login
Content-Type: application/json

{
  "username": "C181059",
  "password": "test1234"
}

###
POST http://localhost/nest-api/submissions
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlcm5hbWUiOiJDMTgxMDU5IiwibmFtZSI6IkZhaGltIFNoYWhyaWVyIiwiaWF0IjoxNjQ1OTY3NDIwfQ.y1h4R5gZ095zXQ9Jz7XZVFLZ_FqO_ahIzfAC98dt9lc;
Content-Type: application/json

{
  "link": "https://codeforces.com/problemset/problem/1617/B",
  "solve_time": 65,
  "verdict": "AC",
  "solved_at": "2022-02-25T02:57:28.354Z"
}