export const testCases = [
  {
    id: 1,
    title: "Codeforces Test 1",
    link: "https://codeforces.com/contest/1617/problem/A",
    expect: {
      pid: "CF-1617A",
      name: "Forbidden Subsequence",
      tags: ["constructive algorithms", "greedy", "sortings", "strings"],
      difficulty: 800,
      judge_id: 1,
      link: "https://codeforces.com/contest/1617/problem/A",
    },
  },
  {
    id: 3,
    title: "Codeforces Gym 1",
    link: "https://codeforces.com/gym/103677/problem/A",
    expect: {
      pid: "Gym-103677A",
      name: "Raiser Mais",
      tags: [],
      difficulty: 0,
      judge_id: 1,
      link: "https://codeforces.com/gym/103677/problem/A",
    },
  },
  {
    id: 4,
    title: "Codeforces Group 1",
    link: "https://codeforces.com/group/MWSDmqGsZm/contest/219158/problem/L",
    expect: {
      pid: "CF-219158L",
      name: "The Brothers",
      tags: [],
      difficulty: 0,
      judge_id: 1,
      link: "https://codeforces.com/group/MWSDmqGsZm/contest/219158/problem/L",
    },
  },
  {
    id: 5,
    title: "CodeChef Test 1",
    link: "https://www.codechef.com/START15C/problems/NPAIRS",
    expect: {
      pid: "CC-NPAIRS",
      name: "Nice Pairs",
      tags: ["string", "brute force"],
      difficulty: 1564,
      judge_id: 2,
      link: "https://www.codechef.com/problems/NPAIRS",
    },
  },
  {
    id: 6,
    title: "CodeChef Test 2",
    link: "https://www.codechef.com/problems/MANIPULATE",
    expect: {
      pid: "CC-MANIPULATE",
      name: "Ezio and Guards",
      tags: ["conditional statements"],
      difficulty: 427,
      judge_id: 2,
      link: "https://www.codechef.com/problems/MANIPULATE",
    },
  },
  {
    id: 7,
    title: "CSES Test 1",
    link: "https://cses.fi/problemset/task/1736",
    expect: {
      pid: "CSES-1736",
      name: "Polynomial Queries",
      tags: [],
      difficulty: 0,
      judge_id: 3,
      link: "https://cses.fi/problemset/task/1736",
    },
  },
  {
    id: 8,
    title: "UVa Test 1",
    link: "https://onlinejudge.org/index.php?option=com_onlinejudge&Itemid=8&page=show_problem&problem=2421",
    expect: {
      pid: "UVA-11426",
      name: "GCD - Extreme (II)",
      tags: [],
      difficulty: 0,
      judge_id: 4,
      link: "https://onlinejudge.org/index.php?option=com_onlinejudge&Itemid=8&page=show_problem&problem=2421",
    },
  },
  {
    id: 9,
    title: "Toph Test 1",
    link: "https://toph.co/p/i-did-not-do-the-assignment",
    expect: {
      pid: "Toph-i-did-not-do-the-assignment",
      name: "I Did Not Do the Assignment",
      tags: ["brute force", "implementation", "number theory"],
      difficulty: 0,
      judge_id: 5,
      link: "https://toph.co/p/i-did-not-do-the-assignment",
    },
  },
  {
    id: 10,
    title: "SPOJ Test 1",
    link: "https://www.spoj.com/problems/AGGRCOW/",
    expect: {
      pid: "SPOJ-AGGRCOW",
      name: "Aggressive cows",
      tags: [],
      difficulty: 0,
      judge_id: 6,
      link: "https://www.spoj.com/problems/AGGRCOW",
    },
  },
  {
    id: 11,
    title: "HackerRank Test 1",
    link: "https://www.hackerrank.com/challenges/2d-array/problem?isFullScreen=true",
    expect: {
      name: "2D Array - DS",
      pid: "HR-2d-array",
      tags: [],
      difficulty: 0,
      judge_id: 7,
      link: "https://www.hackerrank.com/challenges/2d-array",
    },
  },
  {
    id: 12,
    title: "HackerRank Test 2",
    link: "https://www.hackerrank.com/contests/bootcamp-2021female-mirror-contest/challenges/picking-fruits-1",
    expect: {
      name: "Solve Picking Fruits",
      pid: "HR-picking-fruits-1",
      tags: [],
      difficulty: 0,
      judge_id: 7,
      link: "https://www.hackerrank.com/contests/bootcamp-2021female-mirror-contest/challenges/picking-fruits-1",
    },
  },
  {
    id: 13,
    title: "LightOJ Test 1",
    link: "https://lightoj.com/problem/lighting-system-design",
    expect: {
      pid: "LOJ-1295",
      name: "Lighting System Design",
      tags: [],
      difficulty: 0,
      judge_id: 8,
      link: "https://lightoj.com/problem/lighting-system-design",
    },
  },
  {
    id: 14,
    title: "Atcoder Test 1",
    link: "https://atcoder.jp/contests/arc123/tasks/arc123_a",
    expect: {
      pid: "AC-arc123_a",
      name: "Arithmetic Sequence",
      tags: [],
      difficulty: 0,
      judge_id: 9,
      link: "https://atcoder.jp/contests/arc123/tasks/arc123_a",
    },
  },
  {
    id: 15,
    title: "Eolymp Test 1",
    link: "https://eolymp.com/en/problems/9655",
    expect: {
      pid: "Eolymp-9655",
      name: "Mr. Nine and his love for mangoes",
      tags: [],
      difficulty: 0,
      judge_id: 10,
      link: "https://www.eolymp.com/en/problems/9655",
    },
  },
  {
    id: 16,
    title: "LeetCode Test 1",
    link: "https://leetcode.com/problems/first-bad-version",
    expect: {
      pid: "LC-278",
      name: "First Bad Version",
      tags: [],
      difficulty: 0,
      judge_id: 12,
      link: "https://leetcode.com/problems/first-bad-version",
    },
  },
  {
    id: 17,
    title: "Timus Test 1",
    link: "https://acm.timus.ru/problem.aspx?space=1&num=1203",
    expect: {
      pid: "Tim-1203",
      name: "Scientific Conference",
      tags: [],
      difficulty: 0,
      judge_id: 13,
      link: "https://acm.timus.ru/problem.aspx?space=1&num=1203",
    },
  },
  {
    id: 18,
    title: "CodeToWin Test 1",
    link: "https://codeto.win/problem/1154",
    expect: {
      pid: "CW-1154",
      name: "Easy ??",
      tags: [],
      difficulty: 0,
      judge_id: 14,
      link: "https://codeto.win/problem/1154",
    },
  },
  {
    id: 19,
    title: "Kattis OJ Test 1",
    link: "https://open.kattis.com/problems/hello",
    expect: {
      pid: "KT-hello",
      name: "Hello World!",
      tags: [],
      difficulty: 0,
      judge_id: 17,
      link: "https://open.kattis.com/problems/hello",
    },
  },
]
